<a href="https://colab.research.google.com/github/YasminaWaked/spamEmailDetection/blob/main/email_spam_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/data_bases/emails.csv')

In [ ]:
df.head()

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
0,Email 1,0,0,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Email 2,8,13,24,6,6,2,102,1,27,...,0,0,0,0,0,0,0,1,0,0
2,Email 3,0,0,1,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Email 4,0,5,22,0,5,1,51,2,10,...,0,0,0,0,0,0,0,0,0,0
4,Email 5,7,6,17,1,5,2,57,0,9,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
df.tail()

,Email No.,the,to,ect,and,for,of,a,you,hou,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
5167,Email 5168,2,2,2,3,0,0,32,0,0,...,0,0,0,0,0,0,0,0,0,0
5168,Email 5169,35,27,11,2,6,5,151,4,3,...,0,0,0,0,0,0,0,1,0,0
5169,Email 5170,0,0,1,1,0,0,11,0,0,...,0,0,0,0,0,0,0,0,0,1
5170,Email 5171,2,7,1,0,2,1,28,2,0,...,0,0,0,0,0,0,0,1,0,1
5171,Email 5172,22,24,5,1,6,5,148,8,2,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [ ]:
df.describe()

,the,to,ect,and,for,of,a,you,hou,in,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
count,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,...,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000,5172.000000
mean,6.640565,6.188128,5.143852,3.075599,3.124710,2.627030,55.517401,2.466551,2.024362,10.600155,...,0.005027,0.012568,0.010634,0.098028,0.004254,0.006574,0.004060,0.914733,0.006961,0.290023
std,11.745009,9.534576,14.101142,6.045970,4.680522,6.229845,87.574172,4.314444,6.967878,19.281892,...,0.105788,0.199682,0.116693,0.569532,0.096252,0.138908,0.072145,2.780203,0.098086,0.453817
min,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,12.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.000000,3.000000,1.000000,1.000000,2.000000,1.000000,28.000000,1.000000,0.000000,5.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,8.000000,7.000000,4.000000,3.000000,4.000000,2.000000,62.250000,3.000000,1.000000,12.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,210.000000,132.000000,344.000000,89.000000,47.000000,77.000000,1898.000000,70.000000,167.000000,223.000000,...,4.000000,7.000000,2.000000,12.000000,3.000000,4.000000,3.000000,114.000000,4.000000,1.000000

In [ ]:
df.corr()

,the,to,ect,and,for,of,a,you,hou,in,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
the,1.000000,0.852715,0.337249,0.841200,0.784112,0.796397,0.784451,0.471392,0.303621,0.845670,...,0.008926,0.075479,0.225586,0.223426,0.101768,0.129466,0.127019,0.341878,0.051021,-0.004421
to,0.852715,1.000000,0.375480,0.825474,0.781971,0.752722,0.896466,0.508513,0.347993,0.881759,...,0.013250,0.101247,0.232847,0.255793,0.093322,0.091639,0.120059,0.406666,0.071388,0.055277
ect,0.337249,0.375480,1.000000,0.272863,0.369777,0.178028,0.400009,0.155783,0.974152,0.298387,...,0.134339,0.031431,0.046080,0.061550,0.004393,-0.007690,0.004368,0.141460,0.002492,-0.120782
and,0.841200,0.825474,0.272863,1.000000,0.751287,0.809665,0.815196,0.476764,0.235953,0.874276,...,0.005151,0.104454,0.272963,0.253440,0.151980,0.084147,0.124766,0.400225,0.042484,0.114364
for,0.784112,0.781971,0.369777,0.751287,1.000000,0.681457,0.744098,0.495852,0.329051,0.762659,...,0.022168,0.041775,0.236213,0.213631,0.134469,0.067151,0.121057,0.301074,0.038126,-0.003101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
military,0.129466,0.091639,-0.007690,0.084147,0.067151,0.073004,0.111685,0.006498,0.005429,0.120620,...,-0.002249,-0.002979,0.043408,0.104297,0.041300,1.000000,0.055227,0.049524,0.010835,0.064850
allowing,0.127019,0.120059,0.004368,0.124766,0.121057,0.108786,0.105358,0.082757,-0.000966,0.138099,...,-0.002675,-0.003543,-0.005130,0.018550,0.276001,0.055227,1.000000,0.096212,-0.003995,0.011279
ff,0.341878,0.406666,0.141460,0.400225,0.301074,0.444252,0.464473,0.195058,0.114210,0.448303,...,0.005403,0.073690,0.130356,0.164296,0.114092,0.049524,0.096212,1.000000,0.049690,0.135479
dry,0.051021,0.071388,0.002492,0.042484,0.038126,0.026403,0.093822,0.028883,0.000601,0.077751,...,-0.003373,0.035028,-0.006468,0.018939,-0.003137,0.010835,-0.003995,0.049690,1.000000,-0.006260
Prediction,-0.004421,0.055277,-0.120782,0.114364,-0.003101,0.197234,0.107776,0.130293,-0.128340,0.154055,...,-0.030375,-0.031694,0.098775,0.064315,0.038161,0.064850,0.011279,0.135479,-0.006260,1.000000

In [ ]:
x = df.iloc[:,1:3001]
x

,the,to,ect,and,for,of,a,you,hou,in,...,enhancements,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry
0,0,0,1,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8,13,24,6,6,2,102,1,27,18,...,0,0,0,0,0,0,0,0,1,0
2,0,0,1,0,0,0,8,0,0,4,...,0,0,0,0,0,0,0,0,0,0
3,0,5,22,0,5,1,51,2,10,1,...,0,0,0,0,0,0,0,0,0,0
4,7,6,17,1,5,2,57,0,9,3,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,2,2,2,3,0,0,32,0,0,5,...,0,0,0,0,0,0,0,0,0,0
5168,35,27,11,2,6,5,151,4,3,23,...,0,0,0,0,0,0,0,0,1,0
5169,0,0,1,1,0,0,11,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5170,2,7,1,0,2,1,28,2,0,8,...,0,0,0,0,0,0,0,0,1,0
5171,22,24,5,1,6,5,148,8,2,23,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
y = df.iloc[:,-1].values
y

array([0, 0, 0, ..., 1, 1, 0])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state = 1)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(stop_words = 'english')

In [ ]:
vect.fit(X_train)

CountVectorizer(stop_words='english')

In [ ]:
vect.vocabulary_

{'ect': 743,
 'hou': 1152,
 'enron': 793,
 'com': 438,
 'gas': 1001,
 'deal': 601,
 'meter': 1556,
 'hpl': 1159,
 'corp': 527,
 'know': 1343,
 'need': 1639,
 'forwarded': 968,
 'new': 1651,
 'mmbtu': 1591,
 'price': 1914,
 'daren': 583,
 'company': 455,
 'let': 1389,
 'xls': 2720,
 'farmer': 893,
 'attached': 171,
 'information': 1234,
 'message': 1551,
 'day': 598,
 'time': 2485,
 'http': 1173,
 'th': 2463,
 'volume': 2636,
 'mail': 1473,
 'contract': 511,
 'month': 1602,
 'robert': 2146,
 'sitara': 2282,
 'texas': 2459,
 'nom': 1661,
 'energy': 787,
 'pec': 1803,
 'questions': 1994,
 'www': 2715,
 'deals': 604,
 'volumes': 2637,
 'pm': 1864,
 'ena': 781,
 'file': 919,
 'email': 774,
 'just': 1318,
 'change': 372,
 'like': 1399,
 'flow': 942,
 'net': 1645,
 'following': 950,
 'production': 1942,
 'want': 2644,
 'original': 1738,
 'ticket': 2479,
 'make': 1483,
 'report': 2079,
 'march': 1495,
 'contact': 499,
 'days': 599,
 'list': 1411,
 'nomination': 1666,
 'april': 144,
 'number': 1685,
 'sale': 2173,
 'don': 695,
 'thanks': 2465,
 'business': 299,
 'help': 1114,
 'july': 1315,
 'forward': 967,
 'font': 952,
 'free': 973,
 'daily': 578,
 'use': 2588,
 'order': 1731,
 'today': 2493,
 'fw': 990,
 'set': 2240,
 'plant': 1856,
 'statements': 2354,
 'gary': 1000,
 'oil': 1709,
 'line': 1405,
 'sales': 2174,
 'effective': 756,
 'tenaska': 2446,
 'june': 1316,
 'nbsp': 1634,
 'north': 1674,
 'america': 105,
 'week': 2664,
 'january': 1290,
 'service': 2237,
 'purchase': 1981,
 'height': 1112,
 'agreement': 73,
 'work': 2702,
 'tap': 2428,
 'group': 1065,
 'year': 2725,
 'based': 209,
 'transport': 2526,
 'think': 2468,
 'available': 189,
 'changes': 374,
 'services': 2238,
 'smith': 2290,
 'send': 2223,
 'management': 1489,
 'stock': 2365,
 'sent': 2228,
 'll': 1421,
 'office': 1701,
 'needs': 1641,
 'cotten': 536,
 'did': 656,
 'actuals': 28,
 'money': 1600,
 'looking': 1445,
 'pills': 1842,
 'online': 1715,
 'request': 2085,
 'look': 1443,
 'desk': 638,
 'ami': 107,
 'george': 1016,
 'chokshi': 400,
 'point': 1866,
 'delivery': 626,
 'friday': 975,
 'does': 689,
 'size': 2286,
 'august': 181,
 'product': 1941,
 'pat': 1788,
 'width': 2678,
 'iv': 1284,
 'noms': 1669,
 'address': 36,
 'sure': 2407,
 'october': 1695,
 'future': 989,
 'market': 1497,
 'mary': 1505,
 'vance': 2607,
 'melissa': 1541,
 'said': 2171,
 'internet': 1257,
 'account': 9,
 'link': 1407,
 'hsc': 1169,
 'rate': 2006,
 'people': 1810,
 'pipeline': 1845,
 'best': 236,
 'actual': 26,
 'end': 784,
 'home': 1143,
 'houston': 1156,
 'tu': 2544,
 'high': 1126,
 'team': 2435,
 'products': 1943,
 'currently': 570,
 'spot': 2332,
 'receive': 2024,
 'good': 1044,
 'going': 1038,
 'process': 1932,
 'feb': 903,
 'monday': 1599,
 'info': 1232,
 'david': 595,
 'lloyd': 1423,
 'click': 421,
 'subject': 2385,
 'jackie': 1285,
 'december': 608,
 'total': 2506,
 'na': 1627,
 'lisa': 1410,
 've': 2613,
 'september': 2231,
 'hours': 1154,
 'resources': 2101,
 'aol': 124,
 'february': 904,
 'investment': 1264,
 'issue': 1278,
 'duke': 718,
 'pay': 1795,
 'way': 2654,
 'global': 1030,
 'computron': 468,
 'place': 1848,
 'offer': 1697,
 'natural': 1633,
 'activity': 23,
 'eastrans': 734,
 'graves': 1056,
 'right': 2135,
 'prices': 1916,
 'date': 590,
 'john': 1305,
 'utilities': 2595,
 'november': 1684,
 'clynes': 427,
 'jan': 1288,
 'securities': 2213,
 'meeting': 1538,
 'susan': 2409,
 'hplc': 1160,
 'julie': 1314,
 'able': 2,
 'received': 2025,
 'align': 86,
 'term': 2448,
 'id': 1184,
 'revised': 2127,
 'thursday': 2477,
 'pg': 1824,
 'fee': 906,
 'hplno': 1162,
 'trading': 2518,
 'additional': 34,
 'site': 2283,
 'txu': 2552,
 'data': 588,
 'wellhead': 2670,
 'reply': 2078,
 'taylor': 2433,
 'news': 1652,
 'unify': 2567,
 'michael': 1563,
 'provide': 1967,
 'note': 1675,
 'access': 7,
 'lannou': 1356,
 'tuesday': 2546,
 'review': 2124,
 'great': 1057,
 'tom': 2496,
 'long': 1441,
 'save': 2185,
 'section': 2211,
 'nd': 1635,
 'million': 1573,
 'check': 388,
 'trade': 2513,
 'bob': 256,
 'created': 558,
 'steve': 2364,
 'prior': 1921,
 'copy': 524,
 'continue': 507,
 'numbers': 1686,
 'world': 2707,
 'demand': 629,
 'hanks': 1086,
 'contracts': 512,
 'phone': 1829,
 'transaction': 2520,
 'customer': 572,
 'possible': 1885,
 'pefs': 1804,
 'meyers': 1560,
 'months': 1604,
 'special': 2319,
 'used': 2589,
 'regarding': 2049,
 'software': 2294,
 'howard': 1157,
 'support': 2405,
 'buy': 305,
 'young': 2730,
 'meters': 1557,
 'believe': 229,
 'gcs': 1009,
 'cec': 355,
 'entered': 800,
 'control': 513,
 'dec': 607,
 'face': 880,
 'create': 557,
 'weissman': 2668,
 'st': 2338,
 'color': 435,
 'come': 439,
 'supply': 2404,
 'brian': 277,
 'hplo': 1164,
 'correct': 530,
 'customers': 573,
 'web': 2659,
 'allocation': 92,
 'soon': 2303,
 'using': 2593,
 'development': 648,
 'mark': 1496,
 'low': 1456,
 'power': 1890,
 'problem': 1928,
 'tickets': 2480,
 'border': 263,
 'performance': 1815,
 'manager': 1490,
 'rates': 2007,
 'center': 360,
 'companies': 454,
 'risk': 2138,
 'details': 642,
 'needed': 1640,
 'international': 1256,
 'field': 916,
 'doc': 683,
 'fuel': 981,
 'lee': 1382,
 'paid': 1762,
 'start': 2347,
 'index': 1222,
 'include': 1212,
 'nominations': 1667,
 'act': 18,
 'pricing': 1917,
 'scheduled': 2192,
 'gathering': 1004,
 'type': 2553,
 'href': 1167,
 'aimee': 79,
 'feel': 908,
 'fuels': 982,
 'getting': 1019,
 'advice': 51,
 'increase': 1218,
 'path': 1789,
 'sell': 2220,
 'works': 2705,
 'issues': 1280,
 'enronxgate': 796,
 'camp': 319,
 'form': 961,
 'security': 2214,
 'financial': 928,
 'family': 889,
 'xp': 2721,
 'plan': 1852,
 'current': 569,
 'src': 2337,
 'spreadsheet': 2333,
 'allen': 88,
 'wednesday': 2663,
 'read': 2013,
 'working': 2704,
 'wynne': 2716,
 'add': 30,
 'deliveries': 624,
 'buyback': 306,
 'allocated': 90,
 'firm': 932,
 'james': 1287,
 'marketing': 1498,
 'tx': 2551,
 'results': 2114,
 'got': 1046,
 'stocks': 2366,
 'calpine': 317,
 'operations': 1723,
 'position': 1882,
 'logistics': 1435,
 'fax': 897,
 'cost': 534,
 'party': 1781,
 'zero': 2733,
 'pops': 1875,
 'old': 1712,
 'pt': 1973,
 'scheduling': 2195,
 'flowed': 943,
 'dollars': 693,
 'update': 2576,
 'gco': 1008,
 'katy': 1323,
 'including': 1215,
 'follow': 949,
 'yahoo': 2723,
 'suite': 2394,
 'error': 819,
 'past': 1786,
 'page': 1760,
 'stop': 2368,
 'changed': 373,
 'book': 259,
 'program': 1948,
 'better': 237,
 'operating': 1720,
 'equistar': 815,
 'cotton': 537,
 'aep': 57,
 'state': 2351,
 'ees': 753,
 'rita': 2140,
 'provided': 1968,
 'employees': 779,
 'period': 1817,
 'morning': 1608,
 'cd': 351,
 'hotmail': 1150,
 'entex': 804,
 'swing': 2415,
 'real': 2016,
 'exchange': 842,
 'tomorrow': 2498,
 'lst': 1463,
 'counterparty': 542,
 'parker': 1773,
 'person': 1819,
 'follows': 951,
 'valid': 2600,
 'visit': 2630,
 'little': 1416,
 'professional': 1944,
 'quality': 1989,
 'confirm': 479,
 'megan': 1540,
 'brenda': 273,
 'windows': 2689,
 'im': 1194,
 'storage': 2369,
 'accounting': 11,
 'called': 314,
 'ranch': 2003,
 'tax': 2431,
 'problems': 1929,
 'case': 342,
 'teco': 2442,
 'fact': 883,
 'unsubscribe': 2575,
 'coastal': 429,
 'rodriguez': 2149,
 'love': 1455,
 'acton': 24,
 'shut': 2271,
 'pipe': 1844,
 'project': 1951,
 'hope': 1144,
 'limited': 1402,
 'invoice': 1269,
 'credit': 560,
 'survey': 2408,
 'ray': 2008,
 'carlos': 335,
 'wanted': 2645,
 'ic': 1183,
 'scott': 2199,
 'years': 2726,
 'charlie': 382,
 'soft': 2293,
 'notice': 1678,
 'advise': 52,
 'addition': 33,
 'donald': 696,
 'lsk': 1461,
 'wish': 2695,
 'katherine': 1320,
 'website': 2660,
 'hplnl': 1161,
 'schumack': 2198,
 'prescription': 1903,
 'cover': 551,
 'shares': 2253,
 'cash': 343,
 'imbalance': 1197,
 'united': 2571,
 'handle': 1083,
 'big': 241,
 'style': 2384,
 'clear': 417,
 'producer': 1938,
 'weekend': 2665,
 'city': 411,
 'requested': 2086,
 'stone': 2367,
 'left': 1383,
 'payment': 1798,
 'mobil': 1594,
 'shows': 2270,
 'small': 2288,
 'confirmed': 481,
 'technology': 2441,
 'meet': 1537,
 'extend': 871,
 'life': 1397,
 'intended': 1248,
 'sherlyn': 2258,
 'schedule': 2191,
 'letter': 1392,
 'box': 266,
 'richard': 2131,
 'lamphier': 1353,
 'complete': 460,
 'release': 2061,
 'newsletter': 1654,
 'anita': 113,
 'clem': 420,
 'having': 1097,
 'herod': 1119,
 'beginning': 225,
 'papayoti': 1768,
 'try': 2542,
 'mike': 1570,
 'enter': 799,
 'estimates': 826,
 'location': 1430,
 'cut': 575,
 'question': 1993,
 'things': 2467,
 'personal': 1820,
 'feedback': 907,
 'cialis': 407,
 'area': 146,
 'dow': 702,
 'terms': 2451,
 'central': 361,
 'necessary': 1638,
 'man': 1487,
 'run': 2162,
 'reason': 2020,
 'midcon': 1566,
 'charge': 377,
 'president': 1908,
 'listed': 1413,
 'meds': 1536,
 'thomas': 2470,
 'thought': 2472,
 'capital': 327,
 'added': 31,
 'ask': 155,
 'weeks': 2666,
 'investing': 1263,
 'commercial': 444,
 'star': 2346,
 'easy': 736,
 'view': 2628,
 'extended': 872,
 'lauri': 1369,
 'beaumont': 219,
 'union': 2568,
 'times': 2486,
 'open': 1719,
 'cause': 347,
 'monthly': 1603,
 'action': 19,
 'offers': 1700,
 'industry': 1231,
 'states': 2355,
 'mailto': 1478,
 'probably': 1927,
 'neal': 1636,
 'second': 2210,
 'stephanie': 2361,
 'download': 703,
 'flash': 937,
 'agree': 71,
 'mcf': 1521,
 'transfer': 2523,
 'doing': 691,
 'important': 1207,
 'basis': 212,
 'different': 662,
 'final': 925,
 'koch': 1347,
 'exxon': 877,
 'remove': 2075,
 'microsoft': 1564,
 'interested': 1252,
 'application': 131,
 'sept': 2230,
 'mg': 1561,
 'write': 2711,
 'lp': 1459,
 'east': 733,
 'requirements': 2091,
 'code': 430,
 'value': 2605,
 'thank': 2464,
 'exploration': 865,
 'mid': 1565,
 'dfarmer': 652,
 'receipt': 2023,
 'thu': 2476,
 'afternoon': 64,
 'late': 1364,
 'enserch': 797,
 'coming': 442,
 'bank': 203,
 'response': 2105,
 'tell': 2445,
 'shipping': 2263,
 'night': 1660,
 'events': 832,
 'cynthia': 576,
 'lsp': 1462,
 'close': 424,
 'legal': 1384,
 'country': 543,
 'direct': 666,
 'expected': 852,
 'ces': 367,
 'corporation': 529,
 'options': 1730,
 'really': 2019,
 'voip': 2633,
 'nominated': 1664,
 'latest': 1367,
 'potential': 1889,
 'priced': 1915,
 'edward': 751,
 'valero': 2599,
 'material': 1510,
 'stack': 2340,
 'victor': 2624,
 'redeliveries': 2035,
 'loss': 1448,
 'remember': 2072,
 'baumbach': 215,
 'option': 1729,
 'private': 1924,
 'longer': 1442,
 'aware': 195,
 'included': 1213,
 'drugs': 714,
 'public': 1975,
 'reinhardt': 2058,
 'version': 2620,
 'hesse': 1124,
 'discuss': 675,
 'related': 2059,
 'asked': 156,
 'say': 2188,
 'viagra': 2621,
 'revision': 2128,
 'bgcolor': 239,
 'kind': 1339,
 'pro': 1926,
 'completed': 461,
 'health': 1103,
 'ready': 2015,
 'plans': 1855,
 'registered': 2054,
 'regards': 2051,
 'carthage': 340,
 'zone': 2736,
 'away': 196,
 'computer': 466,
 'systems': 2417,
 'industrial': 1229,
 'mentioned': 1547,
 'told': 2495,
 'growth': 1069,
 'sold': 2295,
 'track': 2510,
 'reports': 2081,
 'south': 2310,
 'rd': 2010,
 'jim': 1299,
 'costs': 535,
 'image': 1195,
 'expect': 850,
 'return': 2117,
 'physical': 1833,
 'el': 766,
 'browser': 288,
 'donna': 697,
 'stacey': 2339,
 'begin': 224,
 'china': 397,
 'duty': 721,
 'approximately': 142,
 'showing': 2268,
 'unit': 2570,
 'jones': 1309,
 'hard': 1093,
 'verify': 2619,
 'updated': 2577,
 'eol': 812,
 'cs': 566,
 'orders': 1734,
 'talk': 2424,
 'trying': 2543,
 'base': 208,
 'given': 1025,
 'server': 2235,
 'source': 2308,
 'pathed': 1790,
 'strong': 2380,
 'bryan': 290,
 'directly': 668,
 'risks': 2139,
 'major': 1482,
 'users': 2591,
 'purchases': 1983,
 'oo': 1716,
 'karen': 1319,
 'luong': 1467,
 'level': 1394,
 'required': 2090,
 'delivered': 623,
 'portfolio': 1880,
 'riley': 2137,
 'ali': 85,
 'easttexas': 735,
 'poorman': 1873,
 'bellamy': 231,
 'assistance': 163,
 'gif': 1020,
 'thing': 2466,
 'retail': 2116,
 'didn': 657,
 'valley': 2603,
 'department': 632,
 'cleburne': 419,
 'allow': 94,
 'gpgfin': 1051,
 'answer': 118,
 'items': 1282,
 'paste': 1787,
 'avila': 192,
 'taken': 2421,
 'mm': 1590,
 'nguyen': 1656,
 'ensure': 798,
 'reference': 2044,
 'hall': 1081,
 'later': 1365,
 'lone': 1439,
 'user': 2590,
 'methanol': 1558,
 'facility': 882,
 'network': 1648,
 'spoke': 2330,
 'tabs': 2419,
 'taking': 2423,
 'status': 2357,
 'considered': 493,
 'purchased': 1982,
 'says': 2190,
 'paliourg': 1765,
 'dy': 723,
 'jeff': 1294,
 'businesses': 300,
 'fred': 972,
 'transportation': 2527,
 'apache': 125,
 'morris': 1609,
 'nov': 1683,
 'brand': 270,
 'federal': 905,
 'statement': 2353,
 'oasis': 1687,
 'reflect': 2046,
 'assets': 159,
 'lamadrid': 1352,
 'general': 1012,
 'bridge': 278,
 'ability': 1,
 'oct': 1694,
 'play': 1858,
 'enrononline': 795,
 'compliance': 464,
 'spam': 2317,
 'availability': 188,
 'king': 1340,
 'understanding': 2562,
 'chance': 371,
 'quick': 1995,
 'effort': 758,
 'points': 1867,
 'reliantenergy': 2067,
 'fixed': 934,
 'short': 2266,
 'hill': 1130,
 'cheryl': 392,
 'aepin': 58,
 'key': 1332,
 'understand': 2561,
 'valign': 2601,
 'capacity': 326,
 'game': 996,
 'took': 2501,
 'bring': 281,
 'guys': 1077,
 'god': 1036,
 'green': 1061,
 'care': 333,
 'withers': 2696,
 'property': 1960,
 'hub': 1174,
 'johnson': 1306,
 'employee': 778,
 'wants': 2646,
 'albrecht': 83,
 'meaning': 1527,
 'expectations': 851,
 'mx': 1626,
 'moved': 1614,
 'cernosek': 364,
 'matter': 1513,
 'devon': 650,
 'calls': 316,
 'worldwide': 2709,
 'records': 2033,
 'removed': 2076,
 'lose': 1447,
 'large': 1358,
 'referenced': 2045,
 'walker': 2642,
 'iferc': 1189,
 'enw': 810,
 'ponton': 1870,
 'eileen': 765,
 'ship': 2259,
 'enerfin': 786,
 'jennifer': 1296,
 'looks': 1446,
 'staff': 2341,
 'pc': 1801,
 'target': 2430,
 'waha': 2639,
 'making': 1485,
 'cp': 554,
 'impact': 1204,
 'partner': 1778,
 'immediately': 1203,
 'shall': 2249,
 'channel': 376,
 'takes': 2422,
 'sat': 2182,
 'hear': 1104,
 'went': 2672,
 'travel': 2528,
 'listing': 1414,
 'approved': 140,
 'processing': 1935,
 'early': 728,
 'sally': 2175,
 'starting': 2349,
 'distribution': 681,
 'tejas': 2443,
 'transactions': 2521,
 'stay': 2358,
 'earl': 726,
 'superty': 2403,
 'doesn': 690,
 'reserves': 2096,
 'includes': 1214,
 'choose': 401,
 'adobe': 44,
 'publisher': 1978,
 'paso': 1782,
 'cornhusker': 526,
 'training': 2519,
 'markets': 1499,
 'content': 505,
 'solution': 2299,
 'shell': 2256,
 'jpg': 1311,
 'print': 1920,
 'drive': 710,
 'pain': 1763,
 'password': 1785,
 'half': 1080,
 'herrera': 1120,
 'saturday': 2184,
 'moopid': 1605,
 'hotlist': 1149,
 'balance': 200,
 'super': 2401,
 'vacation': 2597,
 'sex': 2247,
 'happy': 1092,
 'excess': 841,
 'existing': 849,
 'fund': 987,
 'stella': 2359,
 'share': 2250,
 'sign': 2272,
 'wells': 2671,
 'won': 2699,
 'text': 2461,
 'card': 331,
 'tisdale': 2489,
 'fwd': 991,
 'appreciate': 134,
 'non': 1670,
 'experience': 858,
 'savings': 2186,
 'settlements': 2243,
 'draft': 705,
 'couple': 545,
 'informed': 1235,
 'biz': 247,
 'watch': 2652,
 'plus': 1863,
 'sun': 2399,
 'expense': 855,
 'images': 1196,
 'land': 1354,
 'occur': 1692,
 'flowing': 944,
 'mar': 1494,
 'terry': 2452,
 'darren': 586,
 'cheap': 386,
 'weight': 2667,
 'dynegy': 724,
 'activities': 22,
 'mr': 1617,
 'format': 962,
 'attention': 176,
 'entire': 805,
 'photoshop': 1831,
 'williams': 2684,
 'instructions': 1245,
 'neon': 1644,
 'janet': 1289,
 'contains': 504,
 'ago': 70,
 'friends': 977,
 'boas': 255,
 'music': 1625,
 'certain': 365,
 'liz': 1420,
 'svcs': 2412,
 'record': 2031,
 'fast': 894,
 'dave': 594,
 'held': 1113,
 'mind': 1578,
 'ua': 2555,
 'publication': 1976,
 'differ': 660,
 'comments': 443,
 'fun': 984,
 'rest': 2109,
 'instant': 1243,
 'agent': 68,
 'communications': 452,
 'director': 669,
 'partners': 1779,
 'investors': 1267,
 'expedia': 854,
 'kevin': 1331,
 'assist': 162,
 'safe': 2169,
 'approval': 138,
 'allocate': 89,
 'black': 248,
 'intrastate': 1261,
 'document': 686,
 'eric': 818,
 'hakemack': 1079,
 'expired': 862,
 'lower': 1457,
 'active': 21,
 'secure': 2212,
 'cc': 350,
 'determine': 643,
 'press': 1909,
 'colspan': 436,
 'missing': 1586,
 'jill': 1298,
 'discussion': 677,
 'relief': 2068,
 'respect': 2102,
 'specific': 2321,
 'technologies': 2440,
 'al': 82,
 'holmes': 1142,
 'white': 2674,
 'yesterday': 2728,
 'medical': 1532,
 'pinion': 1843,
 'sorry': 2305,
 'men': 1546,
 'leave': 1380,
 'pass': 1783,
 'video': 2626,
 'gomes': 1042,
 'doctor': 684,
 'projects': 1953,
 'limit': 1401,
 'air': 80,
 'knle': 1342,
 'pharmacy': 1826,
 'confirmation': 480,
 'opportunity': 1728,
 'involve': 1272,
 'notify': 1682,
 'gtc': 1070,
 ...}

In [ ]:
vect.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['abdv',
 'ability',
 'able',
 'ac',
 'accept',
 'acceptance',
 'accepted',
 'access',
 'according',
 'account',
 'accountant',
 'accounting',
 'accounts',
 'accuracy',
 'accurate',
 'achieve',
 'acquire',
 'acquisition',
 'act',
 'action',
 'actions',
 'active',
 'activities',
 'activity',
 'acton',
 'acts',
 'actual',
 'actually',
 'actuals',
 'ad',
 'add',
 'added',
 'adding',
 'addition',
 'additional',
 'additionally',
 'address',
 'addressed',
 'addresses',
 'adjust',
 'adjusted',
 'adjustment',
 'adjustments',
 'administration',
 'adobe',
 'adonis',
 'adult',
 'advance',
 'advanced',
 'advantage',
 'advertisement',
 'advice',
 'advise',
 'advised',
 'advises',
 'advisor',
 'aeor',
 'aep',
 'aepin',
 'affect',
 'affected',
 'affiliate',
 'affordable',
 'africa',
 'afternoon',
 'age',
 'agency',
 'agenda',
 'agent',
 'aggressive',
 'ago',
 'agree',
 'agreed',
 'agreement',
 'agreements',
 'agua',
 'ahead',
 'ail',
 'aim',
 'aimee',
 'air',
 'airmail',
 'al',
 'albrecht',
 'alert',
 'ali',
 'align',
 'alland',
 'allen',
 'allocate',
 'allocated',
 'allocating',
 'allocation',
 'allocations',
 'allow',
 'allowed',
 'allowing',
 'allows',
 'alpine',
 'alt',
 'alternative',
 'amazing',
 'amazon',
 'amelia',
 'amended',
 'america',
 'american',
 'ami',
 'amounts',
 'analysis',
 'analyst',
 'analysts',
 'anderson',
 'anita',
 'announce',
 'announced',
 'announces',
 'annual',
 'answer',
 'answers',
 'anti',
 'anticipated',
 'anticipates',
 'anytime',
 'aol',
 'apache',
 'apparently',
 'appear',
 'appears',
 'apple',
 'applicable',
 'application',
 'applications',
 'apply',
 'appreciate',
 'appreciated',
 'approach',
 'appropriate',
 'approval',
 'approve',
 'approved',
 'approx',
 'approximately',
 'apr',
 'april',
 'aquila',
 'area',
 'areas',
 'aren',
 'arial',
 'armstrong',
 'arrangement',
 'arrangements',
 'art',
 'asap',
 'ask',
 'asked',
 'asking',
 'asset',
 'assets',
 'assigned',
 'assignment',
 'assist',
 'assistance',
 'associated',
 'association',
 'assume',
 'assumptions',
 'assurance',
 'atleast',
 'att',
 'attached',
 'attachment',
 'attachments',
 'attempt',
 'attend',
 'attention',
 'auction',
 'audio',
 'audit',
 'aug',
 'august',
 'austin',
 'australia',
 'authority',
 'auto',
 'automatically',
 'availabilities',
 'availability',
 'available',
 'avails',
 'average',
 'avila',
 'avoid',
 'award',
 'aware',
 'away',
 'awesome',
 'baby',
 'bad',
 'balance',
 'bammel',
 'bane',
 'bank',
 'banking',
 'bankruptcy',
 'bar',
 'barrett',
 'base',
 'based',
 'baseload',
 'basin',
 'basis',
 'bass',
 'batch',
 'baumbach',
 'baxter',
 'beach',
 'beaty',
 'beaumont',
 'beck',
 'bed',
 'beemer',
 'began',
 'begin',
 'beginning',
 'begins',
 'behalf',
 'beliefs',
 'believe',
 'believes',
 'bellamy',
 'benedict',
 'benefit',
 'benefits',
 'benoit',
 'best',
 'better',
 'beverly',
 'bgcolor',
 'bid',
 'big',
 'biggest',
 'billed',
 'billing',
 'billion',
 'bit',
 'biz',
 'black',
 'blank',
 'block',
 'blood',
 'blue',
 'blvd',
 'board',
 'boas',
 'bob',
 'body',
 'bold',
 'book',
 'booked',
 'books',
 'boost',
 'border',
 'bought',
 'bowen',
 'box',
 'br',
 'braband',
 'brad',
 'brand',
 'brandywine',
 'brazos',
 'brenda',
 'brennan',
 'brent',
 'bretz',
 'brian',
 'bridge',
 'brief',
 'briley',
 'bring',
 'bringing',
 'broadband',
 'broker',
 'brokered',
 'brought',
 'brown',
 'browser',
 'bruce',
 'bryan',
 'bryce',
 'btu',
 'buckley',
 'buddy',
 'budget',
 'build',
 'building',
 'built',
 'business',
 'businesses',
 'bussell',
 'busy',
 'button',
 'buttons',
 'buy',
 'buyback',
 'buyer',
 'buying',
 'ca',
 'cable',
 'cal',
 'calendar',
 'california',
 'called',
 'calling',
 'calls',
 'calpine',
 'came',
 'camp',
 'campaign',
 'canada',
 'canadian',
 'cancel',
 'cannon',
 'cap',
 'capacity',
 'capital',
 'capture',
 'car',
 'carbide',
 'card',
 'cards',
 'care',
 'caribbean',
 'carlos',
 'carriere',
 'carry',
 'cart',
 'carter',
 'carthage',
 'cartwheel',
 'case',
 'cash',
 'cass',
 'catch',
 'category',
 'cause',
 'caused',
 'causing',
 'cc',
 'cd',
 'cdnow',
 'cds',
 'ce',
 'cec',
 'cell',
 'cellpadding',
 'cellspacing',
 'centana',
 'center',
 'central',
 'cents',
 'ceo',
 'cernosek',
 'certain',
 'certificate',
 'ces',
 'cf',
 'chad',
 'chairman',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channel',
 'charge',
 'charged',
 'charges',
 'charlene',
 'charles',
 'charlie',
 'charlotte',
 'charset',
 'chase',
 'cheap',
 'cheapest',
 'check',
 'checked',
 'chemical',
 'cherry',
 'cheryl',
 'chevron',
 'chief',
 'child',
 'children',
 'china',
 'choate',
 'choice',
 'chokshi',
 'choose',
 'chris',
 'christmas',
 'christy',
 'church',
 'cia',
 'cialis',
 'cilco',
 'cindy',
 'citibank',
 'city',
 'claim',
 'claims',
 'clarification',
 'class',
 'clean',
 'clear',
 'clearance',
 'cleburne',
 'clem',
 'click',
 'clickathome',
 'client',
 'close',
 'closed',
 'club',
 'clynes',
 'coast',
 'coastal',
 'code',
 'coffey',
 'cold',
 'collection',
 'college',
 'color',
 'colspan',
 'column',
 'com',
 'come',
 'comes',
 'comfort',
 'coming',
 'comments',
 'commercial',
 'commission',
 'committed',
 'committee',
 'commodity',
 'common',
 'communicate',
 'communication',
 'communications',
 'community',
 'companies',
 'company',
 'compare',
 'compensation',
 'competition',
 'competitive',
 'complete',
 'completed',
 'completely',
 'completion',
 'compliance',
 'compressor',
 'computer',
 'computers',
 'computron',
 'comstock',
 'concern',
 'concerned',
 'concerning',
 'concerns',
 'conditions',
 'conference',
 'confidence',
 'confidential',
 'confidentiality',
 'confirm',
 'confirmation',
 'confirmed',
 'conflict',
 'congress',
 'connect',
 'connected',
 'connection',
 'connevey',
 'connor',
 'conoco',
 'consemiu',
 'consent',
 'consider',
 'considered',
 'constitutes',
 'construed',
 'consultation',
 'consumer',
 'consumers',
 'contact',
 'contacting',
 'contacts',
 'contain',
 'contained',
 'contains',
 'content',
 'contents',
 'continue',
 'continued',
 'continues',
 'continuing',
 'contract',
 'contracts',
 'control',
 'controls',
 'convenient',
 'conversation',
 'conversion',
 'cook',
 'cooperation',
 'coordinate',
 'copano',
 'copied',
 'copies',
 'copy',
 'corel',
 'cornhusker',
 'corp',
 'corporate',
 'corporation',
 'correct',
 'corrected',
 'correction',
 'correctly',
 'cost',
 'costs',
 'cotten',
 'cotton',
 'couid',
 'couldn',
 'count',
 'counterparties',
 'counterparty',
 'country',
 'county',
 'couple',
 'coupon',
 'course',
 'court',
 'cousino',
 'cove',
 'cover',
 'covered',
 'cowboy',
 'cp',
 'cpr',
 'craig',
 'create',
 'created',
 'creating',
 'credit',
 'critical',
 'cross',
 'crosstex',
 'crow',
 'crude',
 'cs',
 'csikos',
 'ct',
 'current',
 'currently',
 'curve',
 'customer',
 'customers',
 'customerservice',
 'cut',
 'cynthia',
 'da',
 'daily',
 'dallas',
 'dan',
 'daniel',
 'danny',
 'daren',
 'darial',
 'darrel',
 'darren',
 'darron',
 'data',
 'database',
 'date',
 'dated',
 'dates',
 'dating',
 'dave',
 'david',
 'davis',
 'dawn',
 'day',
 'days',
 'deadline',
 'deal',
 'dealer',
 'dealers',
 'deals',
 'death',
 'debt',
 'dec',
 'december',
 'decide',
 'decided',
 'deciding',
 'decision',
 'decisions',
 'decrease',
 'deer',
 'default',
 'defs',
 'degree',
 'del',
 'delay',
 'delete',
 'deliver',
 'delivered',
 'deliveries',
 'delivering',
 'delivery',
 'dell',
 'delta',
 'demand',
 'demokritos',
 'den',
 'department',
 'deposit',
 'der',
 'description',
 'design',
 'designed',
 'desk',
 'desks',
 'desktop',
 'detailed',
 'details',
 'determine',
 'determined',
 'develop',
 'developed',
 'developing',
 'development',
 'device',
 'devon',
 'dewpoint',
 'dfarmer',
 'dial',
 'diamond',
 'diane',
 'did',
 'didn',
 'die',
 'died',
 'differ',
 'difference',
 'different',
 'difficult',
 'digital',
 'diligence',
 'direct',
 'direction',
 'directly',
 'director',
 'disclose',
 'disclosure',
 'discount',
 'discovered',
 'discrepancies',
 'discuss',
 'discussed',
 'discussion',
 'discussions',
 'distribute',
 'distributed',
 'distribution',
 'dl',
 'doc',
 'doctor',
 'doctors',
 'document',
 'documentation',
 'documents',
 'does',
 'doesn',
 'doing',
 'dollar',
 'dollars',
 'dolphin',
 'don',
 'donald',
 'donna',
 'door',
 'dorcheus',
 'double',
 'doubt',
 'dow',
 'download',
 'dr',
 'draft',
 'draw',
 'drill',
 'drilling',
 'driscoll',
 'drive',
 'driver',
 'drop',
 'drug',
 'drugs',
 'dry',
 'dth',
 'dudley',
 'duke',
 'dulce',
 'duplicate',
 'duty',
 'dvd',
 'dy',
 'dynegy',
 'ea',
 'earl',
 'earlier',
 'early',
 'earnings',
 'earthlink',
 'easier',
 'easily',
 'east',
 'eastrans',
 'easttexas',
 'easy',
 'eat',
 'eb',
 'ebs',
 'ecf',
 'ecom',
 'economic',
 'ect',
 'ed',
 'edge',
 'edit',
 'edition',
 'edmondson',
 'edu',
 'education',
 'edward',
 'eel',
 'ees',
 'eff',
 'effect',
 'effective',
 'effects',
 'effort',
 'efforts',
 'egm',
 'egmnom',
 'ehronline',
 'ei',
 'eiben',
 'eileen',
 'el',
 'electric',
 'electronic',
 'eliminate',
 'elizabeth',
 'ellis',
 'elsa',
 'em',
 'email',
 'emails',
 'emerging',
 'emirates',
 'employee',
 'employees',
 'en',
 'ena',
 'encina',
 'encoding',
 'end',
 'ended',
 'enerfin',
 'energy',
 'engel',
 'enhanced',
 'enhancements',
 'enjoy',
 'enquiries',
 'enron',
 'enronavailso',
 'enrononline',
 'enronxgate',
 'enserch',
 'ensure',
 'enter',
 'entered',
 'entering',
 'enterprise',
 'entertainment',
 'entex',
 'entire',
 'entity',
 'entries',
 'entry',
 'environment',
 'enw',
 'eogi',
 'eol',
 'epgt',
 'equipment',
 'equistar',
 'equity',
 'erections',
 'eric',
 'error',
 'errors',
 'especially',
 'est',
 'esther',
 'estimate',
 'estimated',
 'estimates',
 'et',
 'europe',
 'european',
 'evening',
 'event',
 'events',
 'evergreen',
 'ews',
 'ex',
 'exact',
 'exactly',
 'example',
 'examples',
 'exception',
 'excess',
 'exchange',
 'excite',
 'exciting',
 'exclusive',
 'executed',
 'executive',
 'exercise',
 'existing',
 'expect',
 'expectations',
 'expected',
 'expects',
 'expedia',
 'expense',
 'expenses',
 'expensive',
 'experience',
 'experienced',
 'experiencing',
 'expiration',
 'expired',
 'expires',
 'explode',
 'exploration',
 'explore',
 'explosion',
 'express',
 'expressed',
 'ext',
 'extend',
 'extended',
 'extension',
 'external',
 'extra',
 'extremely',
 'exxon',
 'eye',
 'eyes',
 'face',
 'facilities',
 'facility',
 'fact',
 'factor',
 'factors',
 'facts',
 'fall',
 'familiar',
 'family',
 'far',
 'fare',
 'fares',
 'farmer',
 'fast',
 'fat',
 'father',
 'fax',
 'fda',
 'fear',
 'feature',
 'featured',
 'features',
 'feb',
 'february',
 'federal',
 'fee',
 'feedback',
 'feel',
 'fees',
 'feet',
 'felipe',
 'female',
 'ferc',
 'ff',
 'ffffff',
 'field',
 'fields',
 'fight',
 'file',
 'files',
 'filing',
 'filings',
 'filled',
 'filter',
 'final',
 'finally',
 'finance',
 'financial',
 'financing',
 'finding',
 'fine',
 'firm',
 'fix',
 'fixed',
 'fl',
 'flag',
 'flash',
 'fletcher',
 'flight',
 'floor',
 'florida',
 'flow',
 'flowed',
 'flowing',
 'flw',
 'flynn',
 'focus',
 'focused',
 'follow',
 'following',
 'follows',
 'font',
 'fontfont',
 'foot',
 'force',
 'forecast',
 'foreign',
 'foresee',
 'forever',
 'forget',
 'form',
 'format',
 'formosa',
 'forms',
 'formula',
 'forth',
 'forward',
 'forwarded',
 'forwarding',
 'frank',
 'franklin',
 'fred',
 'free',
 'fri',
 'friday',
 'friend',
 'friends',
 'ft',
 'ftar',
 'ftworth',
 'fuel',
 'fuels',
 'fully',
 'fun',
 'function',
 'functionality',
 'fund',
 'funds',
 'future',
 'fw',
 'fwd',
 'fyi',
 'ga',
 'gain',
 'gains',
 'game',
 'games',
 'gap',
 'garrick',
 ...]

In [ ]:
mnb = MultinomialNB(alpha = 1.9) #alpha by default is 1, alpha must always be > 0.
#alpha is the 1 in the formula for Laplace Smoothing (P(words))
mnb.fit(X_train, y_train)
y_pred1  = mnb.predict(X_test)
print("Accuracy Score for Naive Bayes : ", accuracy_score(y_pred1, y_test))

Accuracy Score for Naive Bayes :  0.94276875483372